InvertedPendulum-v2:
  db: data/LQRKalman_demo_InvertedPendulum_1000.pickle
  obs_dim:
    pomdp: [0,1]
    mdp: [0,1,2,3]
  acs_dim: 1

InvertedDoublePendulum-v2:
  db:  data/sac_demo_InvertedDoublePendulum-v2.pickle
  obs_dim:
    pomdp: [0,1,2,3,4,8,9,10]  
    mdp: [0,1,2,3,4,5,6,7,8,9,10]
  acs_dim: 1

HalfCheetah-v2:
  db:  data/sac_demo_HalfCheetah-v2.pickle
  obs_dim:
    pomdp: [0,1,2,3,4,5,6,7]
    mdp: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  acs_dim: 6

Hopper-v2:
  db: data/sac_demo_Hopper-v2.pickle
  obs_dim:
    pomdp: [0,1,2,3,4]
    mdp: [0,1,2,3,4,5,6,7,8,9,10]
  acs_dim: 3

Walker2d-v2:
  db: data/sac_demo_Walker2d-v2.pickle
  obs_dim:
    pomdp: [0,1,2,3,4,5,6,7]
    mdp: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  acs_dim: 6

Swimmer-v2:
  db: data/sac_demo_Swimmer-v2.pickle
  obs_dim:
    pomdp: [0,1,2,3,4]
    mdp: [0,1,2,3,4,5,6,7]
  acs_dim: 2
 



    


