learning_params:  
  prev_acs: True
  learning_rate: 0.0001
  gamma: 1.0
  hidden_dim: 128 #16
  belief_dim: 4
  actor_hidden_dim: 128 #16
  decoder_hidden : 64
  batch_size: 32
  epochs: 1000
  process_model: "pomdp"
  network_arch: "RNNVAE"
  task_agnostic: False
  belief_reg: True
  eval_interval: 10 
  shuffle: True
  seq_length: 500
  k: 10
  split: 0.9

