learning_params:  
  prev_acs: True
  learning_rate: 0.0001
  gamma: 1.0
  belief_dim: 8 #16
  actor_hidden_dim: 16 #16
  decoder_hidden : [64, 64]
  batch_size: 32
  epochs: 500
  process_model: "pomdp"
  network_arch: "RNNFF"
  eval_interval: 10 
  shuffle: True
  seq_length: 2000
  split: 0.5
experiment:
  envs: ['InvertedDoublePendulum-v2'] 
  traj_lengths: [10]
  belief_dims: [16]
  prev_acs: [True]
  archs: ["naive", "belief"]