learning_params:  
  prev_acs: True
  learning_rate: 0.0001
  gamma: 1.0
  hidden_dim: 16 #16
  belief_dim: 4
  actor_hidden_dim: 128 #16
  decoder_hidden : 16
  batch_size: 32
  epochs: 500
  process_model: "pomdp"
  network_arch: "RNNVAE"
  task_agnostic: False
  belief_reg: True
  eval_interval: 10 
  shuffle: True
  seq_length: 500
  k: 10
  split: 0.9
  loss_weights:
    decoder:  
      reconstruction: 0.18
      one_fwd: 0.18
      one_bwd: 0.18
      k_fwd: 0.18
      k_bwd: 0.18
    latent: 0.1
    

