learning_params:  
  prev_acs: True
  learning_rate: 0.001
  belief_dim: 64
  actor_hidden_dim: 64
  decoder_hidden : [64, 64]
  batch_size: 32
  epochs: 5
  process_model: "pomdp"
  network_arch: "belief"
  eval_interval: 10 
  shuffle: True
  traj_length: 100
experiment:
  envs: ['InvertedPendulum-v2'] 
  traj_lengths: [10]
  belief_dims: [4, 16, 64]
  prev_acs: [True, False]
  archs: ["naive", "belief"]