prev_acs: True
learning_rate: 0.0001
gamma: 0.9
hidden_dim: 32 #16
belief_dim: 4
policy_hidden: 32 #16
decoder_hidden : 32
batch_size: 32
acs_encoding_dim: 32
epochs: 300
ae_state_dict: "checkpoints/ae"
policy_state_dict: "checkpoints/policy"
eval_interval: 5 
seq_length: 100
k: 5
split: 0.8
loss_weights:
  reconstruction: 1
  obs_one_fwd: 1
  obs_one_bwd: 1
  obs_k_fwd: 1
  obs_k_bwd: 1
  acs_1_fwd: 1
  acs_k_fwd: 1