prev_acs: False
learning_rate: 0.0001
gamma: 1
hidden_dim: 32 #16
belief_dim: 4
policy_hidden: 32 #16
decoder_hidden : 32
batch_size: 32
epochs: 10
vae_state_dict: "checkpoints/vae"
policy_state_dict: "checkpoints/policy"
eval_interval: 5 
seq_length: 100
k: 5
split: 0.9
loss_weights:
  reconstruction: 1
  one_fwd: 1
  one_bwd: 1
  k_fwd: 1
  k_bwd: 1
  acs: 0.2
  kld: 0.1